export const CONTACT = {
  name: "Sete Lírios",
  subtitle: "Farmácia de Manipulação",
  phone1: "(16) 3722-3777",
  phone2: "(16) 3722-3026",
  phone3: "(16) 9 9336-3643",
  whatsapp: "(16) 99244-0470",
  whatsappLink: "https://wa.me/5516992440470",
  phoneHref: "tel:551637223777",
  mapsHref: "https://maps.google.com/?q=Av.+Brasil+815+Franca+SP",
  email: "contato@setelirios.com.br",
  emailHref: "mailto:contato@setelirios.com.br",
  address: "Av. Brasil, 815 — Vila Aparecida, Franca/SP",
  cep: "14401-240",
  hours: "Seg-Sex 08h-20h | Sáb 08h-18h",
  rating: 5.0,
  reviews: 4,
  followers: 8630,
  instagram: "@farmaciasetelirios",
  instagramHref: "https://instagram.com/farmaciasetelirios",
  services: ["Fórmulas alopáticas", "Alta Performance", "Manipulação Magistral", "Fitoterápicos"],
  category: "Medical & health",
};

export const categories = [
  {
    name: "Manipulação Magistral",
    slug: "manipulacao-magistral",
    icon: "FlaskRound",
    sub: [
      "Hormônios Biodenticos",
      "Reposição Hormonal",
      "Dermatologia (cremes/géis)",
      "Emagrecimento",
      "Vitaminas Personalizadas",
      "Fitoterápicos",
      "Ortomolecular",
    ],
  },
  {
    name: "Alta Performance",
    slug: "alta-performance",
    icon: "Zap",
    sub: [
      "Creatina Manipulada",
      "Whey Protein",
      "Pré-Treino",
      "BCAA",
      "Glutamina",
      "Termogênicos",
      "Repositores Eletrolíticos",
    ],
  },
  {
    name: "Dermatologia",
    slug: "dermatologia",
    icon: "Sparkles",
    sub: [
      "Cremes Clareadores",
      "Géis de Limpeza",
      "Loções Hidratantes",
      "Protetor Solar Manipulado",
      "Tratamento para Acne",
      "Antienvelhecimento",
      "Clareamento Íntimo",
    ],
  },
  {
    name: "Fitoterápicos",
    slug: "fitoterapicos",
    icon: "Leaf",
    sub: [
      "Calmantes Naturais",
      "Para Sono",
      "Imunidade",
      "Digestão",
      "Energia Vital",
      "Adaptógenos",
      "Chás Medicinais",
    ],
  },
  {
    name: "Bem-Estar",
    slug: "bem-estar",
    icon: "Heart",
    sub: [
      "Vitaminas e Minerais",
      "Ômega 3",
      "Colágeno",
      "Probióticos",
      "Saúde Digestiva",
      "Sono e Relaxamento",
      "Saúde da Mulher",
    ],
  },
  {
    name: "Hormônios",
    slug: "hormonios",
    icon: "Activity",
    sub: [
      "Reposição Hormonal Feminina",
      "Reposição Hormonal Masculina",
      "Tireoide",
      "Melatonina",
      "DHEA",
      "Progesterona",
      "Testosterona",
    ],
  },
];

export const featuredProducts = [
  {
    name: "Creatina Manipulada Pura",
    category: "Alta Performance",
    price: "R$ 89,90",
    parcel: "ou 3x de R$ 29,97",
    badge: "Mais Vendido",
    badgeColor: "bg-green/10 text-green",
    image: null,
  },
  {
    name: "Vitamina D3 5.000 UI",
    category: "Bem-Estar",
    price: "R$ 54,90",
    parcel: "ou 3x de R$ 18,30",
    badge: "Promoção",
    badgeColor: "bg-brand/10 text-brand",
    image: null,
  },
  {
    name: "Colágeno Hidrolisado",
    category: "Dermatologia",
    price: "R$ 72,50",
    parcel: "ou 3x de R$ 24,17",
    badge: "Novo",
    badgeColor: "bg-green/10 text-green",
    image: null,
  },
  {
    name: "Ômega 3 EPA/DHA",
    category: "Bem-Estar",
    price: "R$ 65,00",
    parcel: "ou 3x de R$ 21,67",
    badge: null,
    badgeColor: null,
    image: null,
  },
  {
    name: "Melatonina 3mg",
    category: "Hormônios",
    price: "R$ 38,50",
    parcel: "ou 3x de R$ 12,83",
    badge: "Fitoterápico",
    badgeColor: "bg-green/10 text-green",
    image: null,
  },
  {
    name: "Protetor Solar FPS 60",
    category: "Dermatologia",
    price: "R$ 95,00",
    parcel: "ou 3x de R$ 31,67",
    badge: "Manipulado",
    badgeColor: "bg-brand/10 text-brand",
    image: null,
  },
];